apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: privategpt-client
  annotations:
    autoscaling.knative.dev/min-scale: "1"
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: react-frontend
    apps.tanzu.vmware.com/has-tests: true

spec:
  params:
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: node
  source:
    git:
      url: https://github.com/spuchol81/gpt-on-premises
      ref:
        branch: main
